all: clean
	cd ./baseIO && $(MAKE)
	cd ./commandHandler && $(MAKE)
	cd ./timer && $(MAKE)
	cd ./trainIO && $(MAKE)
	cd ./trainStatus && $(MAKE)
	cd ./trainIO && $(MAKE)
	cd ./view && $(MAKE)
	cd ./pollCyclle && $(MAKE)

clean:
	cd ./baseIO && $(MAKE) clean
	cd ./commandHandler && $(MAKE) clean
	cd ./timer && $(MAKE) clean
	cd ./trainIO && $(MAKE) clean
	cd ./trainStatus && $(MAKE) clean
	cd ./trainIO && $(MAKE) clean
	cd ./view && $(MAKE) clean
	cd ./pollCyclle && $(MAKE) clean
